version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "production"

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
